### ISSUE TITLE
Add option to "shard" execution of the `checks.remotesettings.attachments_availability` check

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/telescope#1447]
See https://github.com/mozilla-it/webservices-infra/pull/2011#issuecomment-2115277602 

For example, by bucket:

```toml
[checks.remotesettings-prod.attachments-main]
description = "Attachments are all available via CDN"
module = "checks.remotesettings.attachments_availability"
params.server = "https://firefox.settings.services.mozilla.com/v1"
params.buckets = ["main", "blocklists"]

[checks.remotesettings-prod.attachments-main]
description = "Attachments are all available via CDN"
module = "checks.remotesettings.attachments_availability"
params.server = "https://firefox.settings.services.mozilla.com/v1"
params.buckets = ["security-state"]

```

or have a range parameter to split it based on number of attachments:

```toml
[checks.remotesettings-prod.attachments-part1]
description = "Attachments are all available via CDN"
module = "checks.remotesettings.attachments_availability"
params.server = "https://firefox.settings.services.mozilla.com/v1"
params.slice_percent = [0, 49]

[checks.remotesettings-prod.attachments-part2]
description = "Attachments are all available via CDN"
module = "checks.remotesettings.attachments_availability"
params.server = "https://firefox.settings.services.mozilla.com/v1"
params.slice_percent = [50, 100]
